version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://keycloakdb:5432/keycloak"
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - 18080:8080
    command: start-dev
    depends_on:
      - keycloakdb

  keycloakdb:
    image: postgres:15.2
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    ports:
      - 15432:5432
    volumes:
      - keycloakdb_data:/var/lib/postgresql/data

  tododb:
    image: postgres:15.2
    environment:
      POSTGRES_USER: ${TODO_DB_USER}
      POSTGRES_PASSWORD: ${TODO_DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - tododb_data:/var/lib/postgresql/data
      # - ./database/Sql:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
    environment:
      MODE: ${TODO_APP_MODE}
    depends_on:
      - tododb
    ports:
      - 5000:5000

  frontend:
    build:
      context: ./frontend
      target: production
      network: host
    ports:
      - 4000:80

  nginx:
    image: nginx
    environment:
      TZ: Asia/Tokyo
      NGINX_HOST: ${NGINX_HOST}
      NGINX_PORT: ${NGINX_PORT}
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    depends_on:
      - backend
      - frontend

volumes:
  keycloakdb_data:
  tododb_data:
